### PR TITLE
Remove unnecessary code duplication

### PR DESCRIPTION
**Pull request by guizmaii**
I'm sure to understand why you duplicated this code in the `js` and `jvm` dir.

I think that you don't need to do that.

You can just put the code in the `shared` dir and it'll be compiled for the two platforms.

LMKWYT

### CODE REVIEW

**Comment by zakpatterson** [comment]
Thanks so much! 

So a couple things: Due to #164, I'm not running the tests for the JS backend in CI.

Also, you'll see that on [the server version of UserDetail](https://github.com/clovellytech/http4s-modules/blob/master/modules/auth/comm/jvm/src/main/scala/UserDetail.scala), there's a joinTime field which is an `Instant`, but [on the JS side](https://github.com/clovellytech/http4s-modules/blob/b605ad0/modules/auth/comm/js/src/main/scala/UserDetail.scala), it's String. 

This is because `java.time.Instant` doesn't exist in js.

So I think if you run the tests through the browser, as described in #164, you'll see a "get a real java time" message thrown from circe's not-java-time package.

I'm not super happy with the way I've implemented it either, so I do think this is a good thing to improve. Thanks so much for trying it out.

**Comment by guizmaii** [comment]
> Also, you'll see that on the server version of UserDetail, there's a joinTime field which is an Instant, but on the JS side, it's String.

Oh. Sorry I missed that 😅

**Comment by zakpatterson** [comment]
Ah not at all, I didn't mean to suggest we abandon this, do you think it's an ok way to handle the difference in field types?

**Comment by guizmaii** [comment]
There's this project that can maybe help you: https://github.com/scala-js/scala-js-java-time

**Comment by guizmaii** [comment]
Or even this one which seems more maintained: https://github.com/cquiroz/scala-java-time

**Comment by zakpatterson** [comment]
The second one looks good to me. Initially I was trying to avoid adding this, but you've already noticed complexity in this project that would be removed by adding this library, and future modules will undoubtedly benefit from elegant handling of timestamps. So I think adding that sounds great!

**Comment by zakpatterson** [comment]
I merged in the end-to-end testing that just got done in #164 #166, so now we see the not-java-time error from deserializing into Instant on the js side.

So yes we should proceed with this approach and adding scala-java-time
```
[info]   Cause: scala.NotImplementedError: Get a real java.time

[info]   at $c_s_NotImplementedError.$c_jl_Throwable.fillInStackTrace__jl_Throwable(file:///home/travis/build/clovellytech/http4s-modules/modules/auth/client/js/target/scala-2.12/scalajs-bundler/test/auth-client-test-fastopt-bundle.js:33098:14)

[info]   at $c_s_NotImplementedError.$c_jl_Throwable.init___T__jl_Throwable__Z__Z(file:///home/travis/build/clovellytech/http4s-modules/modules/auth/client/js/target/scala-2.12/scalajs-bundler/test/auth-client-test-fastopt-bundle.js:33216:10)

[info]   at scala.NotImplementedError.<init>(file:///home/travis/build/clovellytech/http4s-modules/modules/auth/client/js/target/scala-2.12/scalajs-bundler/test/auth-client-test-fastopt-bundle.js:56361:58)

[info]   at java.time.package$.unimplemented(file:///home/travis/build/clovellytech/http4s-modules/modules/auth/client/js/target/scala-2.12/scalajs-bundler/test/auth-client-test-fastopt-bundle.js:5862:40)
```

**Comment by guizmaii** [comment]
@zakpatterson why the tests are green while there's an error?

**Comment by guizmaii** [comment]
With my last commit: 

```java
[info] - A login should create usable session *** FAILED ***
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: 5717 was not less than 5000
[info]     Location: (AuthEndpointsProperties.scala:76)
[info]     Occurred when passed generated values (
[info]       arg0 = UserRequest(xtpaeAwebwbpdeoyrwznzUapbcQtjvucr,bxyuxCoydeqamkxsniltogotkqidxarJmudwqzlx)
[info]     )
[info] - A bad password return 400
[info] ScalaTest
[info] Run completed in 16 seconds, 787 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
```

Why `failed 0` ? 🤔

**Comment by zakpatterson** [comment]
> With my last commit:
> 
> ```scala
> [info] - A login should create usable session *** FAILED ***
> [info]   TestFailedException was thrown during property evaluation.
> [info]     Message: 5717 was not less than 5000
> [info]     Location: (AuthEndpointsProperties.scala:76)
> [info]     Occurred when passed generated values (
> [info]       arg0 = UserRequest(xtpaeAwebwbpdeoyrwznzUapbcQtjvucr,bxyuxCoydeqamkxsniltogotkqidxarJmudwqzlx)
> [info]     )
> [info] - A bad password return 400
> [info] ScalaTest
> [info] Run completed in 16 seconds, 787 milliseconds.
> [info] Total number of tests run: 0
> [info] Suites: completed 0, aborted 0
> [info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
> ```
> 
> Why `failed 0` ?

I think it's because of parallel execution. You're seeing a summary from some other test underneath that one, but the real summary is a bit lower in the build.

**Comment by zakpatterson** [comment]
> @zakpatterson why the tests are green while there's an error?

The script I put up is just not returning the correct exit value, i'll put up another branch and merge it into this one for testing.

**Comment by zakpatterson** [comment]
Ok, I think the build is pretty solid now. Let me know what you think.

**Comment by zakpatterson** [comment]
I think the only error was from `not-java-time` still being included. I need this scala-time business for my next feature, so I'm going to go ahead and merge this if it works. Thanks @guizmaii !

**Pull request merged**
